name: Swift Tests

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ develop ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        swift: ["5.9"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Swift
      uses: swift-actions/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v
    
    - name: Run tests with code coverage
      run: swift test --enable-code-coverage
    
    - name: Generate code coverage report
      run: |
        xcrun llvm-cov export -format="lcov" \
          .build/debug/SwiftRandomKitPackageTests.xctest/Contents/MacOS/SwiftRandomKitPackageTests \
          -instr-profile .build/debug/codecov/default.profdata \
          > coverage.lcov
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.lcov
        fail_ci_if_error: false 